apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-node
  namespace: argocd
spec:
  project: default #nama projek pada argocd
  source:
    repoURL: https://github.com/gedharizka/k8s-manifest.git
    targetRevision: main #branch
    path: docker-node #path folder config
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: test-application
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
