apiVersion: v1
kind: Service
metadata:
  name: docker-node-service
  labels:
    run: docker-node
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    run: docker-node
